// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CopyToClipboard(arg1) {
  return window['go']['main']['AppService']['CopyToClipboard'](arg1);
}

export function GetAppInfo() {
  return window['go']['main']['AppService']['GetAppInfo']();
}

export function OpenFileDialog() {
  return window['go']['main']['AppService']['OpenFileDialog']();
}

export function OpenOutputFolder(arg1) {
  return window['go']['main']['AppService']['OpenOutputFolder'](arg1);
}
