// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CopyToClipboard(arg1:string):Promise<void>;

export function GetAppInfo():Promise<main.AppInfo>;

export function OpenFileDialog():Promise<string>;

export function OpenOutputFolder(arg1:string):Promise<void>;
