// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ListMicDevices() {
  return window['go']['main']['DeviceService']['ListMicDevices']();
}

export function ListSpeakerDevices() {
  return window['go']['main']['DeviceService']['ListSpeakerDevices']();
}
