// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetState() {
  return window['go']['main']['ResultService']['GetState']();
}

export function SetState(arg1) {
  return window['go']['main']['ResultService']['SetState'](arg1);
}
