// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {agent} from '../models';

export function GetState():Promise<Record<string, any>>;

export function SetState(arg1:agent.MeetingState):Promise<void>;
